CREATE TABLE lessons(
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(250) NOT NULL,
  content VARCHAR(250) NOT NULL,
  video_link TEXT UNIQUE,
  position BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  update_at TIMESTAMPTZ,
  course_link TEXT UNIQUE NOT NULL
  );

CREATE TABLE courses(
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(250) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  update_at TIMESTAMPTZ
);

CREATE TABLE moduls(
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(250) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  update_at TIMESTAMPTZ
);

CREATE TABLE programs(
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(250) NOT NULL,
  price DECIMAL NOT NULL,
  type VARCHAR(250) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  update_at TIMESTAMPTZ
);
